name: docker-misc-${CONTAINER_NAME}
services:
  demucs:
    container_name: ${CONTAINER_NAME}
    image: xserrat/facebook-demucs:latest
    build: .
    volumes:
      - ./gradio:/app
      - ./input:/data/input
      - ./output:/data/output
      - ./models:/data/models
      - ${HF_HOME}:/root/.cache/huggingface
      - ${TORCH_HOME}:/root/.cache/torch    
    ports:
      - ${DEMUCS_PORT}:7860
    working_dir: /lib/demucs
    entrypoint: ['python3', '/app/app.py']
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
